### ISSUE TITLE
nil value global 'icon"

### ISSUE THREAD

**Issue by BoonyCat** [Thadah/helix-plugins#1]
[ERROR] gamemodes/XXXX/schema/plugins/lootcontainers/entities/entities/nut_itemcontainer/cl_init.lua:12: attempt to index global 'icon' (a nil value)
  1. OnPopulateEntityInfo - gamemodes/XXXX/schema/plugins/lootcontainers/entities/entities/nut_itemcontainer/cl_init.lua:12
   2. SetEntity - gamemodes/helix/gamemode/core/derma/cl_tooltip.lua:283
    3. unknown - gamemodes/helix/gamemode/core/hooks/cl_hooks.lua:543

**Comment by Thadah** [comment]
Hi!
The plugin should go inside `gamemodes/XXXX/plugins/lootcontainers`, not `gamemodes/XXXX/schema/plugins/lootcontainers`. 

I believe that is why it is failing, as the code is taken from the official Helix plugin _containers_ [ix_container.lua#L145](https://github.com/NebulousCloud/helix/blob/dc986499a265595a874cefc78e9b691c3cc01c69/plugins/containers/entities/entities/ix_container.lua#L145)

If you still have problems running it after this change, please let me know! I'll keep the issue open for now.

**Comment by BoonyCat** [comment]
Hey Thadah! Thanks for the speedy response! :)

I've changed the directory and got the following:
[ERROR] gamemodes/XXXX/plugins/lootcontainers/entities/entities/nut_itemcontainer/cl_init.lua:12: attempt to index global 'icon' (a nil value)
  1. OnPopulateEntityInfo - gamemodes/XXXX/plugins/lootcontainers/entities/entities/nut_itemcontainer/cl_init.lua:12
   2. SetEntity - gamemodes/helix/gamemode/core/derma/cl_tooltip.lua:283
    3. unknown - gamemodes/helix/gamemode/core/hooks/cl_hooks.lua:543
    
 Some additional info:
 The loot does spawn, though not in the correct model, it seems to use the model models/props_junk/garbage_bag001a.mdl, regardless of input /lootaddspawn <model>.

**Comment by Thadah** [comment]
About the error, you might be right, I'm going to make a small fix to see if that was the problem.

About the models, you must add any new models you want to use so the plugin knows how big to make the inventory for it. It will default to the garbage bag anyways if the model path is invalid.
The models are in [sh_models.lua](https://github.com/Thadah/helix-plugins/blob/master/lootcontainers/sh_models.lua).

**Comment by BoonyCat** [comment]
Alright, thank you! :) I'll test the fix as soon as it's available and provide feedback.

**Comment by BoonyCat** [comment]
![image](https://github.com/Thadah/helix-plugins/assets/108937910/866db95e-0b3c-461a-9835-597b00f64f46)
Perfect, no more errors!

Thanks for the swift fix! Really appreciated. :)

**Comment by Thadah** [comment]
Thank you for letting me know!
