### ISSUE TITLE
Changing model does not work

### ISSUE THREAD

**Issue by BoonyCat** [Thadah/helix-plugins#2]
Hey Thadah, me again, sorry.

I've tried to change the model of the lootspawn to one defined in the sh_models.lua file, namely the file cabinet.
Path to model is "models/props_lab/filecabinet02.mdl".

Command executed was:
![image](https://github.com/Thadah/helix-plugins/assets/108937910/4540fa70-95e4-4972-a843-23565b054379)

The result:
![image](https://github.com/Thadah/helix-plugins/assets/108937910/41514967-de4e-442a-b78f-a9ba5e9f1aa1)

sh_models.lua contains the following:
PLUGIN.containerModel["models/props_lab/filecabinet02.mdl"] = {
	name = "File Cabinet",
	desc = "A green metal file cabinet.",
	invType = INV_TYPE_ID,
	openSound = "items/ammocrate_open.wav",
	invData = {
		w = 4,
		h = 4
	}
}

Please let me know if I'm doing something wrong. Thank you for your time and effort.

**Comment by BoonyCat** [comment]
Tried the same, with quotation marks, just to make sure, but same result.
![image](https://github.com/Thadah/helix-plugins/assets/108937910/c47433d6-6c05-44e7-970b-2b7206c180c7)

**Comment by Thadah** [comment]
I'll have a look at it asap, thanks for letting me know!

**Comment by Thadah** [comment]
Now the models should apply correctly. I also made the code a bit smarter and allowed any Garry's Mod model as a container, using the inventory size of the bag as a default
